spring:
  zipkin:
    enabled: true
    base-url: http://zipkin:9411/
  rabbitmq:
    host: ${productms.bus.rabbitmq.host:rabbitmq-master}
    port: ${productms.bus.rabbitmq.port:5672}
  cloud:
    stream:
      bindings:
        webaudit-out:
         binder: rabbit-binder
         destination: ex.webaudit         
         producer:
          bindQueue: false
          routing-key-expression: '"rk.webaudit.shim.him"'
          routing-key: '"rk.webaudit.shim.him"'
          routingKeyExpression: '''rk.webaudit.shim.him'''
        discountstream-out:
         binder: kafka-binder
         destination: TX-DISCOUNTSTREAM
         contentType: application/json
         partitionCount: 2
         replication-factor: 2
      binders:
      
        rabbit-binder:
         type: rabbit
         environment:
            spring:
              rabbitmq:
               host: rabbitmq-master
               port: 5672

        kafka-binder:    
         type: kafka
         environment:
          spring:
            cloud:
             stream:
              kafka:
               binder:
                  brokers: kafka1:9094,kafka2:9095
                  defaultBrokerPort: 9094
                  autoCreateTopics: true
                  autoAddPartitions: true
                  minPartitionCount:  2
                  replicationFactor: 1         
      default-binder: rabbit-binder
    bus:
     trace: 
      enabled: ${configserver.bus.trace:true}
     destination: ${configserver.bus.destination:busXchange}
#ogging:
# pattern: 
#    level: "[%X{X-B3-TraceId} : %X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"
#  level:
#    root: INFO
#    com.ms.bootcamp: INFO   
#discountms.logging.pattern: 
#discountms.logging.root.level: info
#discountms.logging.app.level: debug

discountms.eureka.instance.zone: zone_8761
discountms.eureka.instance.leaseRenewalIntervalInSeconds: 2
discountms.eureka.instance.leaseExpirationDurationInSeconds: 5
discountms.eureka.client.registerWithEureka: true
discountms.eureka.client.fetchRegistry: true
discountms.eureka.client.prefer-same-zone-eureka: true
discountms.eureka.client.service-registry-url: http://eureka-1:8761/eureka
discountms.hystrix.metrics.polling-interval-ms: 3000

discountdata.discountmap.FURNISHING: 7.35
discountdata.discountmap.KITCHENELECTRONIC: 5.22
discountdata.discountmap.MEDICALEQUIPMENT: 5.0
discountdata.discountmap.MOBILEPHONE: 5.0
discountdata.discountmap.MUSICINSTRUMENT: 5.0
discountdata.discountmap.TOY: 1.8